-- Use the Assignments database
USE ASSIGNMENTS;
GO
--==========================================================================
GO
------- Question-7: Display the details where total expenses are greater than 40
		SELECT TOP 10*
		FROM FactsTable
		WHERE Total_Expenses > 40;
GO
--==========================================================================
GO
------- Question-8: What is the average sales in area code 719
		SELECT
			AVG(Sales) AS MeanSales
		FROM FactsTable
		WHERE Area_Code = 719;
GO
--==========================================================================
GO
------- Question-9: Find out the total profit generated by Colorado state
		SELECT 
			SUM(Profit) AS Total_Colorado_Profit
		FROM FactsTable 
		WHERE Area_Code IN 
			(SELECT  Area_Code FROM LocationTable WHERE State = 'Colorado');
GO
--==========================================================================
GO
------- Question-10: Display the average inventory for each product ID.
		SELECT
			ProductId, AVG(Inventory) AS ProductWise_Mean_Inventory
		FROM FactsTable
		GROUP BY ProductId ORDER BY ProductId;
GO
--==========================================================================
GO
------- Question-11:  Display state in a sequential order in a LocationTable
		SELECT
			DISTINCT(State) AS State_Name
		FROM LocationTable ORDER BY State;
GO
--==========================================================================
GO
------- Question-12: Display the average budget of the Product where the average 
------- budget margin should be greater than 100.
		SELECT 
			ProductId, AVG(Budget_Margin) AS AverageBudget
		FROM FactsTable
		GROUP BY ProductId
		HAVING AVG(Budget_Margin) > 100;
GO